# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/99a69d9a-d81d-4c72-99a4-f27bdf814064";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/374ddb26-72f9-423d-80ec-68f5df7f6081"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
